[package]
name = "bissel"
version = "0.1.0"
description = "Robotics-focused publish/request middleware for embedded Linux"
authors = ["Christopher Moran <christopher.and.moran@gmail.com>"]
edition = "2018"

[lib]
name = "bissel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# de/serialization and message sending
serde = {version = "1", default-features = false, features = ["derive"]}
postcard = {version = "0.7", features = ["alloc"]}
# key value store, networking, and async
sled = "0.34.6"
pnet = "0.28"
tokio = { version = "1.14.0", features = ["full", "rt-multi-thread"] }
# command-line utilties
clap = "3"
# logging
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
hex-slice = "0.1"

