[package]
name = "rhiza"
version = "0.1.0"
authors = ["Christopher Moran <christopher.and.moran@gmail.com>"]
edition = "2018"

[lib]
name = "rhiza"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", default-features = false, features = ["derive"]}
postcard = {version = "0.7", features = ["alloc"]}
heapless = "0.7"

sled = "0.34.6"
pnet = "0.28"
tokio = { version = "1.14.0", features = ["full"] }

[dev-dependencies]
serial_test = "0.5.1"